services:
  localstack:
    image: localstack/localstack:stable
    container_name: secure-api-localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      SERVICES: s3,kms
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}

  api:
    build:
      context: .
    container_name: secure-api
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localstack:4566
      S3_BUCKET_NAME: secure-api-artifacts-local
    depends_on:
      localstack:
        condition: service_healthy